[package]
name = "wapm-test"
version = "1.0.0"
description = ""
license = "ISC"

[[module]]
name = "wapm-test"
source = "entry.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "wapm-test"
module = "wapm-test"
